### ISSUE TITLE
OCKNotes not syncing

### ISSUE THREAD

**Issue by ChrisGambrell** [netreconlab/ParseCareKit#74]
When trying to sync an OCKNote, there are issues with establishing pointers. See attached screen shot.

<img width="2197" alt="Screen Shot 2020-11-30 at 5 42 26 PM" src="https://user-images.githubusercontent.com/6411228/100686072-94fb6800-334b-11eb-89ce-66a40d77f321.png">

**Comment by cbaker6** [comment]
@ChrisGambrell thanks submitting! This bug was due to ParseCareKit along with a bug in the dependency in Parse-Swift. It's fixed on the main branch now and the latest version of the CareKitSample-ParseCareKit app has all of the updates.

Let me know if you get a chance to test on your end if the problem is fixed.
